[[mobile-core]]
Mobile Core
-----------

image:https://img.shields.io/:license-Apache2-blue.svg[License, link=http://www.apache.org/licenses/LICENSE-2.0]


The Mobile Core is a central repo for all things related to Mobile on OpenShift.
This repo has the source for:

* Mobile specific UI extensions fo the OpenShift Web Console
* Mobile App Ansible Playbook Bundles (APBs)
* Local Development environment

The following components are maintained in their respective repos:
* Mobile CLI
* Mobile SDKs
* Mobile Services

The Mobile Core brings all of these componments together to create a unified
Mobile developer experience on top of OpenShift.

[[contributing]]
Contributing
~~~~~~~~~~~~

You can develop link:./docs/walkthroughs/local-setup.adoc[locally on your
host]. Please include as much info as possible in Issues and Pull
Requests. Merging to master requires approval from a reviewer and a
passing CI build.

[[communication]]
Communication
~~~~~~~~~~~~~

Daily communication happens on #aerogear on
https://webchat.freenode.net/[freenode IRC]. The
http://lists.jboss.org/pipermail/aerogear-dev/[aerogear-dev@lists.jboss.org
mailing list] is also used for team-wide & community comms.

[[onboarding-resources]]
Onboarding Resources
~~~~~~~~~~~~~~~~~~~~

* Mobile SDKs
** https://github.com/feedhenry/fh-sync-android[Android Sync SDK]
** https://github.com/feedhenry/fh-sync-js[Cordova/Browser Sync SDK]
** https://www.aerogear.org/docs/specs/#push[Push SDKs]
** https://www.npmjs.com/package/keycloak-js[Keycloak JS Adapter]
* Mobile CLI Resources
** https://tour.golang.org/welcome/1[Tour of Go]
* Frontend Resources
** https://github.com/aerogear/mobile-core/tree/master/ui[UI src]
** https://docs.angularjs.org/tutorial[AngularJS PhoneCat Tutorial]
** https://docs.angularjs.org/api[AngularJS API Docs]
** http://www.patternfly.org/[Patternfly]
** https://github.com/openshift/origin-web-console[OpenShift Web Console]
** https://docs.openshift.com/container-platform/3.7/install_config/web_console_customization.html[Customising
the OpenShift Web Console (Extensions]
** https://github.com/openshift/origin-web-catalog[Service
Catalog/OpenShift Mall UI]
* Catalog/Mall, Brokers & Services
** https://docs.openshift.com/container-platform/3.7/architecture/service_catalog/index.html[Service
Catalog]
** https://docs.openshift.com/container-platform/3.7/architecture/service_catalog/ansible_service_broker.html[OpenShift Ansible Broker (OAB) & Ansible Playbook Bundles (APB)]
** https://docs.openshift.com/container-platform/3.7/architecture/service_catalog/template_service_broker.html[Template Service Broker]
** https://github.com/feedhenry/fh-sync-server[fh-sync-server]
** https://github.com/feedhenry/fh-sync-server/blob/master/fh-sync-server-DEVELOPMENT.yaml[fh-sync-server
Template]
** https://github.com/keycloak/keycloak[Keycloak]
** https://github.com/aerogearcatalog/keycloak-apb[Keycloak APB]

[[doing-a-development-release]]
Development Release
~~~~~~~~~~~~~~~~~~~

link:./docs/Release.md[Release]

[[installing-from-a-development-release]]
Installing from a development release
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Effectively all you need to do is add the dockerhub_tag to your install command. An example is show below. Note it is important that the image version exists in dockerhub.

....
make clean
ansible-playbook playbook.yml -e "dockerhub_username=$DOCKERHUB_USERNAME" -e "dockerhub_tag=${TAG}" -e "dockerhub_password=$DOCKERHUB_PASSWORD" -e "dockerhub_org=$DOCKERHUB_APBS_ORG" -e "skip_apb=keycloak-apb" --ask-become-pass
....

By default an `admin` user will be created with cluster edit permissions. To skip creating this user use `--tags=local` with the installer. For example:

```
ansible-playbook playbook.yml -e "dockerhub_username=$DOCKERHUB_USERNAME" -e "dockerhub_tag=${TAG}" -e "dockerhub_password=$DOCKERHUB_PASSWORD" -e "dockerhub_org=$DOCKERHUB_APBS_ORG" --tags=local --ask-become-pass
```
