[[mobile-core]]
Mobile Core
-----------

image:https://img.shields.io/:license-Apache2-blue.svg[License, link=http://www.apache.org/licenses/LICENSE-2.0]

AeroGear on OpenShift is a project that enables set of the mobile enabled services that run natively on Open Shift platform.
This repository is central element of the AeroGear on OpenShift ecosystem that installs the OpenShift platform and the AeroGear components to your local machine. You can then use the OpenShift UI or mobile-cli to work with running OpenShift instance in order to deploy mobile enabled services and configure your mobile client to be able to use those services.

This repository contains:

* Installer for OpenShift and AeroGear OpenShift templates
* Mobile specific UI extensions fo the OpenShift Web Console
* Local Development environment

== Getting Started
=== Installation
Mobile on OpenShift can be installed using Ansible based installer or Minishift

link:https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/local-setup.adoc[Ansible based installer] Sets up mobile on your host machine.

link:https://github.com/aerogear/minishift-mobilecore-addon[Minishift mobile addon] Sets up a minishift vm and installs mobile

== Related components

The following components are maintained in their respective repos:

=== Mobile CLI

Command line client required to perform various operations for OpenShift AeroGear extensions.
link:https://github.com/aerogear/mobile-cli[Mobile CLI] github repository


=== Mobile SDKs

Official list of supported SDK's:

- link:https://github.com/aerogear/aerogear-android-sdk[Android (Java)]
- link:https://github.com/aerogear/aerogear-ios-sdk[iOS (Swift)]
- link:https://github.com/aerogear/aerogear-js-sdk[JavaScript and Cordova SDK]
- link:https://github.com/aerogear/aerogear-xamarin-sdk[Xamarin]

=== Mobile end user templates

Templates that contain the most recent versions of the SDK's

- link:https://github.com/aerogear/android-showcase-template[Android]
- link:https://github.com/aerogear/ios-showcase-template[IOS]
- link:https://github.com/aerogear/cordova-showcase-template[Ionic (Cordova)]
- link:https://github.com/aerogear/xamarin-showcase-template[Xamarin]

=== Mobile Services

Mobile Services will automatically be added to the Service Catalog after running the Mobile Core installer. These services can all be found in the form of Ansible Playbook Bundles (APBs) hosted on the link:https://github.com/aerogearcatalog[aerogearcatalog] organisation on Github.

The Mobile Core brings all APB componments together to create a unified
Mobile developer experience on top of OpenShift.

[[contributing]]
Contributing
~~~~~~~~~~~~

You can develop link:./docs/walkthroughs/local-setup.adoc[locally on your
host]. Please include as much info as possible in Issues and Pull
Requests. Merging to master requires approval from a reviewer and a
passing CI build.

[[communication]]
Communication
~~~~~~~~~~~~~

Daily communication happens on the `##aerogear` and `#asbroker` channels on
link:https://webchat.freenode.net/[freenode IRC]. The
link:https://groups.google.com/forum/#!forum/aerogear[Aerogear
Mailing List] is also used for team-wide & community comms.

[[doing-a-development-release]]
Development Release
~~~~~~~~~~~~~~~~~~~

link:./docs/Release.md[Release]

[[installing-from-a-development-release]]
Installing from a development release
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
make clean
cd installer
./install.sh
```

See our link:./docs/walkthroughs/local-setup.adoc[Local Setup] guide
