[[mobile-core]]
Mobile Core
-----------

image:https://img.shields.io/:license-Apache2-blue.svg[License, link=http://www.apache.org/licenses/LICENSE-2.0]

AeroGear on OpenShift is an project that enables set of the mobile enabled services that run natively on Open Shift platform.
This repository is central element of the AeroGear on OpenShift ecosystem that installs Open Shift platforms and all AeroGear related templates (Ansible APB) to local machine. Developers then can use mobile-cli that is designed to work with running Open Shift instance and perform various tasks and one of the available mobile SDK's. For complete list of the repositories see bellow.

This repository contains:

* Installator for OpenShift and AeroGear OpenShift templates
* Mobile specific UI extensions fo the OpenShift Web Console
* Local Development environment

== Related components

The following components are maintained in their respective repos:

=== Mobile CLI

Command line client required to perform various operations for OpenShift AeroGear extensions
Link: https://github.com/aerogear/mobile-cli

=== Mobile SDKs

Official list of supported SDK's:

- Android (Java) https://github.com/aerogear/aerogear-android-sdk
- iOS (Swift) https://github.com/aerogear/aerogear-ios-sdk
- JavaScript and Cordova SDK https://github.com/aerogear/aerogear-js-sdk
- Xamarin https://github.com/aerogear/aerogear-xamarin-sdk

=== Mobile Services

Mobile services will be installed automatically into ansible broker when running mobile-core installer.
All Ansible Playbook Bundles (APBs) for Apps & Services are hosted on separate organization:

https://github.com/aerogearcatalog

The Mobile Core brings all APB componments together to create a unified
Mobile developer experience on top of OpenShift.

[[contributing]]
Contributing
~~~~~~~~~~~~

You can develop link:./docs/walkthroughs/local-setup.adoc[locally on your
host]. Please include as much info as possible in Issues and Pull
Requests. Merging to master requires approval from a reviewer and a
passing CI build.

[[communication]]
Communication
~~~~~~~~~~~~~

Daily communication happens on the `##aerogear` and `#asbroker` channels on
link:https://webchat.freenode.net/[freenode IRC]. The
link:https://groups.google.com/forum/#!forum/aerogear[Aerogear
Mailing List] is also used for team-wide & community comms.

[[doing-a-development-release]]
Development Release
~~~~~~~~~~~~~~~~~~~

link:./docs/Release.md[Release]

[[installing-from-a-development-release]]
Installing from a development release
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
make clean
cd installer
./install.sh
```

See our link:./docs/walkthroughs/local-setup.adoc[Local Setup] guide
