[[developing-apbs-locally]]
= Developing APBs Locally


This document outlines best practices for Aerogear APB development.
General information about the OpenShift Ansible Broker (OAB) and Ansible Playbook Bundles (APB) is included in the link:https://docs.openshift.com/container-platform/3.6/architecture/service_catalog/ansible_service_broker.html[OpenShift docs].

== Prerequisites

Before doing local development of Aerogear APBs, you should have used the installer in this repo to set up a local OpenShift cluster. link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/walkthroughs/local-setup.adoc[Read the document here.]

Additionally, we need to set up the appropriate permissions.

```bash
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin admin
oc adm policy add-cluster-role-to-user access-asb-role admin
oc login -u admin
password: admin
```

This gives 3 distinct users:

* `developer` who logins in with "regular" perms
* `system:admin` who can't login to UI but is also an admin.
* `admin` who can login to the UI with cluster admin perms. **This is the user we will use for APB development**

== Installing the apb CLI

The `apb` CLI can be installed locally, however we recommend using it wrapped in a Linux container. To create an alias for the dockerized `apb` CLI:

....
alias apb='docker run --rm --privileged -v $PWD:/mnt -v $HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u $UID docker.io/ansibleplaybookbundle/apb-tools'
....


== Creating an APB

We recommend following the link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md[tutorial] on how to write ABPs.

To create a `APB` module:

....
apb init
....

NOTE: Best practice is to name the APB ending with `-apb`.

== Making your APB consumable as a mobile service

When creating an APB for a mobile service, where possible use Kubernetes resources
( rather than Openshift resources ) to ensure compatibility with Openshift and Kubernetes, eg. using 
Kubernetes Deployment instead of openshift DeploymentConfig.


Only one instance of a service is expected in a namespace. If your service is intended to have more
than one service instance consideration must be given to the naming of objects.

=== ConfigMaps Vs Secrets

Separate the public and private configuration information in your APB.

Use *configMaps* for public information that a mobile client will need to use the service. To allow the configMap
to be read by the mobile-cli it must be labeled with *mobile: enabled* and the *serviceName*.

An example of this can be seen link:https://github.com/aerogearcatalog/keycloak-apb/blob/master/roles/provision-keycloak-apb/templates/configmap.yml.j2[here].

[source,yaml]
----
  labels:
    mobile: enabled
    serviceName: my-custom-service
----

It's possible that a mobile client will require some secret information such as an API key. This should be stored in the configMap.

Use *secrets* for private information such as passwords and usernames.

[source,yaml]
----
- k8s_v1_secret:
    name: '{{ myService_secret_name }}'
    namespace: '{{ namespace }}'
    labels:
      name: myService
      mobile: enabled
      serviceName: myService
    string_data:
      admin_username: '{{ ADMIN_NAME }}'
      admin_password: '{{ ADMIN_PASSWORD }}'
----

For more information about this requirement see the original proposal link:https://github.com/aerogear/proposals/blob/master/apbs/create-secret-and-configmap-during-provision.md[here].

=== Specifics of Mobile Service APBs

For Mobile service APBs, make sure there is a `mobile-service` tag inside the `apb.yml` file:

....
...
tags: 
  - mobile-service
....

This tag is used by the serviceCatalog to group the APB with other mobile services.

Inside of the `apb.yml` file, make sure you use include `serviceName:` in the metadata section, like:

....
...
metadata:
  displayName: Aerogear Sync Server
  console.openshift.io/iconClass: icon-nodejs
  serviceName: fh-sync-server
...
....

=== Integrating with the metrics service

To allow Prometheus to auto discover your custom services' metrics endpoint you need to include an annotation when creating the 
Kubernetes service in your provisioning task. More information about integration with the metrics service can be
found link:https://github.com/aerogear/proposals/blob/master/metrics/prometheus-metrics-endpoints-and-auto-discovery.md[here].

[source,yaml]
----
annotations:
  org.aerogear.metrics/plain_endpoint: /my-metrics-endpoint
----

An example can be seen link:https://github.com/aerogearcatalog/keycloak-apb/blob/master/roles/provision-keycloak-apb/tasks/provision-keycloak.yml#L70[here].


You can also link:https://github.com/aerogearcatalog/metrics-apb#how-to-add-a-new-dashboard-while-provisioning-a-service[include a  custom Grafana dashboard] 
for your service.

=== Building an APB

To build an APB:

....
make apb_build
....

Alternatively, if you have set up the alias described above you can directly use `apb build`.

=== Push an APB to a Local Openshift Cluster

Assuming your OpenShift cluster is up and running, you can push the APB image to the local OpenShift Docker Registry with:

....
apb push -o
....

Afterwards your APB is ready to be used from the _Service Catalog_.

[NOTE]
====
* If you push an APB and immediately try to provision it, sometimes it fails. Wait about 20 seconds and try again. This is a link:https://bugzilla.redhat.com/show_bug.cgi?id=1501523[known bug in the OpenShift Ansible Broker].

* Using `make build_and_push` executes all phases at once.
====

=== Configure OpenShift Ansible Broker to use Dockerhub Regsitry

By default, the installer in this repo configures the OpenShift Ansible Broker to list images in the Service Catalog from OpenShift's local docker registry **and** from the `aerogear` organisation in Dockerhub.

You can also configure the OpenShift Ansible Broker to list images from your Dockerhub account.

There is no need to do this for local APB development workflow, but it may be useful to understand how to configure the OpenShift Ansible Broker to use images in a remote regsitry.

....
oc project ansible-service-broker
oc edit configmap broker-config
....

This will allow you to edit the OAB config in your terminal. Under the `registries` list, add another item:

....
- type: dockerhub
  name: <some name>
  org: <your dockerhub username>
  user: <your dockerhub username>
  pass: <your dockerhub password>
  white_list:
    - ".*-apb$"
....

You can also edit the `broker-config` Config Map in the OpenShift web console under the `ansible-service-broker` project. Check the link:https://github.com/openshift/ansible-service-broker/blob/master/docs/config.md[Ansible Service Broker configuration docs] for more examples.

=== Push to Dockerhub Account
Build and push the _APB_ to Dockerhub with the following:

....
make DOCKERORG="my_org" docker_push
....

NOTE: Set `DOCKERHOST="<host>"` to use a different regsitry. The default is `docker.io`.

Then force the OpenShift Ansible Broker to relist images from Dockerhub:

....
apb relist
....

== Debugging an APB 

When you run an `APB` a temporary namespace is created where a pod is created to run the provision process. By default that namespace is deleted when provisioning is complete.

If you want to review logs in that namespace after provisioning, set the following parameter for `broker-config`
```
    openshift:
      keep_namespace: true
```

== Bootstrapping an APB

When configuring the ansible broker
you can force the broker to reload images from your org.

----
apb bootstrap
----

== Testing an APB

Good practice is to have a special playbook for testing, called ``test.yml``. This playbook is used for quick verification of the 
implemented roles within the APB repository. If you include some/all roles (provision, bind, deprovision, unbind) in your
service, you should include a test task for that role so its functionality can be easily verified simply by 
running the ``apb test`` command.

There are examples of PR based testing set up using link:https://github.com/aerogearcatalog/metrics-apb/blob/master/Jenkinsfile[Jenkins] 
and link:https://github.com/ansibleplaybookbundle/mediawiki-apb/blob/master/.travis.yml[Travis CI].

More information about APB testing can be found link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md#test[here].

== Automated Builds

Every `aerogear` APB has a Docker Hub repository set up for hosting images.
When a PR for an APB repository is merged to master, the Docker Hub respository detects this and kicks off an automated build.
If the build is successful, the resulting image is tagged as `latest`, replacing the previous `latest` image for that APB.

=== Setting up an Automated Build for APB Images

IMPORTANT: Docker repositories for APBs need to be created as an 'Automated Build' rather than a 'Repository'. There doesn't seem to be a way to add an automated build to a repository afterwards.

While signed into Docker Hub from a browser:

* Create > Create Automated Build
* Choose Github and allow access to repositories in the aerogearcatalog Github org
* Look for the repo in the list and click it
* Make sure the Repository Namespace & Name are correct e.g. aerogearcatalog/metrics-apb. Visibility public is fine.
* After creating, go to Build Settings
* Configure 'master' branch to build
* Configure tags that match a name of `/^[0-9.]+/` to build
* Save changes and Trigger a build for `master`. If successful, there should be an image with the 'latest' tag.
