[[developing-apbs-locally]]
= Developing APBs Locally


This document outlines best practices for Aerogear APB development.
General information about the OpenShift Ansible Broker (OAB) and Ansible Playbook Bundles (APB) is included in the link:https://docs.openshift.com/container-platform/3.6/architecture/service_catalog/ansible_service_broker.html[OpenShift docs].

== Installing the apb CLI

The `apb` CLI can be installed locally, however we recommend using it wrapped in a Linux container. To create an alias for the dockerized `apb` CLI:

....
alias apb='docker run --rm --privileged -v $PWD:/mnt -v $HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u $UID docker.io/ansibleplaybookbundle/apb-tools'
....


== Creating an APB

We recommend following the link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md[tutorial] on how to write ABPs.

To create a `APB` module:

....
apb init
....

NOTE: Best practice is to name the APB ending with `-apb`.

=== Building an APB

To build an APB:

....
make apb_build
....

=== Pushing to Dockerhub

If you want to push the APB to your own Dockerhub account:

....
make DOCKERORG="my_org" docker_push
....

NOTE: Set `DOCKERHOST` to override the dockerhost default, which is `docker.io`.

=== Pushing APBs to OpenShift Ansible Broker (OAB) locally

. Create a MCP cluster pointing at *your* own docker organisation:
+
....
ansible-playbook playbook.yml -e "dockerhub_username=<dockerusername>" -e "dockerhub_password=<dockerpassword>" -e "dockerhub_org=<USE_THIS_VALUE>" -e "apb_sync=true" --ask-become-pass
....
+
[NOTE]
====
* This copies all the existing APBs in aerogear to the `dockerhub_org` registry.

* Setting `apb_sync=true` pushs all the aerogear catalog to your dockerhub account.

* Developers can use aerogearcatalog organization and openshift local registry for development.
====

. Make the APB:
+
....
make apb_build
....

. Push your ABP to the running ASB of your MCP project:
+
....
make apb_push
....
+
Afterwards your APB is available from the _Service Catalog_.

[NOTE]
====
* When pushing apb it will not be available immediately. 

* Using `make build_and_push` executes all phases at once.
====

== Debugging an APB 

When you run an `APB` a temporary namespace is created where a pod is created to run the provision process. By default that namespace is deleted when provisioning is complete.

If you want to review logs in that namespace after provisioning, set the following parameters for `broker-config`
`keep_namespace_on_error="true"` or `keep_namespace="true"`

== Bootstrapping an APB

When configuring the ansible broker
you can force the broker to reload images from your org.

----
apb bootstrap
----

== Pushing APBs locally

For testing purposes developers may save time by building and using the internal openshift registry.
To publish the ABP to the local OpenShift registry:

----
apb prepare
apb push -o 
----

== Using the mobile-service tag

For MCP enabled _APBs_, make sure we have a `mobile-service` tag inside the `apb.yml` file:

....
...
tags: 
  - mobile-service
....

== Using the servicename label

Inside of the `apb.yml` file, make sure you use the `serviceName:` label, like:

....
...
metadata:
  displayName: Aerogear Sync Server
  console.openshift.io/iconClass: icon-nodejs
  serviceName: fh-sync-server
...
....

== Testing an APB

Currently, there are not many tools for testing. The APB team has a few open Github issues and proposals:

* link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/131[lint command for APB content]
* link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/proposals/testing.md[CI and Image tests]
