[[developing-apbs-locally]]
= Developing APBs Locally


This document outlines best practices for Aerogear APB development.
General information about the OpenShift Ansible Broker (OAB) and Ansible Playbook Bundles (APB) is included in the link:https://docs.openshift.com/container-platform/3.6/architecture/service_catalog/ansible_service_broker.html[OpenShift docs].

== Prerequisites

Before doing local development of Aerogear APBs, you should have used the installer in this repo to set up a local OpenShift cluster. link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/walkthroughs/local-setup.adoc[Read the document here.]

Additionally, the `developer` user in OpenShift needs some extra permissions. Use the `system:admin` user to apply the permissions and then log back in as `developer`.

```bash
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin developer
oc adm policy add-cluster-role-to-user access-asb-role developer
oc login -u developer
```

== Installing the apb CLI

The `apb` CLI can be installed locally, however we recommend using it wrapped in a Linux container. To create an alias for the dockerized `apb` CLI:

....
alias apb='docker run --rm --privileged -v $PWD:/mnt -v $HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u $UID docker.io/ansibleplaybookbundle/apb-tools'
....


== Creating an APB

We recommend following the link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md[tutorial] on how to write ABPs.

To create a `APB` module:

....
apb init
....

NOTE: Best practice is to name the APB ending with `-apb`.

=== Building an APB

To build an APB:

....
make apb_build
....

Alternatively, if you have set up the alias described above you can directly use `apb build`.

=== Push an APB to a Local Openshift Cluster

Assuming your OpenShift cluster is up and running, you can push the APB image to the local OpenShift Docker Registry with:

....
apb push -o
....

Afterwards your APB is ready to be used from the _Service Catalog_.

[NOTE]
====
* When pushing an APB it will not be available immediately. 

* Using `make build_and_push` executes all phases at once.
====

=== Configure OpenShift Ansible Broker to use Dockerhub Regsitry

By default, the installer in this repo configures the OpenShift Ansible Broker to list images in the Service Catalog from OpenShift's local docker registry **and** from the `aerogear` organisation in Dockerhub.

You can configure the OpenShift Ansible Broker to list images from your Dockerhub account as follows:

....
oc project ansible-service-broker
oc edit configmap broker-config
....

This will allow you to edit the OAB config in your terminal. Under the `registries` list, add another item:

....
- type: dockerhub
  name: <some name>
  org: <your dockerhub username>
  user: <your dockerhub username>
  pass: <your dockerhub password>
  white_list:
    - ".*-apb$"
....

You can also edit the `broker-config` Config Map in the OpenShift web console under the `ansible-service-broker` project. Check the link:https://github.com/openshift/ansible-service-broker/blob/master/docs/config.md[Ansible Service Broker configuration docs] for more examples.

=== Push to Dockerhub Account
You can build and push the _APB_ to your own Dockerhub account with the following:

....
make DOCKERORG="my_org" docker_push
....

NOTE: Set `DOCKERHOST` to override the dockerhost default, which is `docker.io`.

== Debugging an APB 

When you run an `APB` a temporary namespace is created where a pod is created to run the provision process. By default that namespace is deleted when provisioning is complete.

If you want to review logs in that namespace after provisioning, set the following parameter for `broker-config`
```
    openshift:
      keep_namespace: true
```

== Bootstrapping an APB

When configuring the ansible broker
you can force the broker to reload images from your org.

----
apb bootstrap
----

== Using the mobile-service tag

For MCP enabled _APBs_, make sure we have a `mobile-service` tag inside the `apb.yml` file:

....
...
tags: 
  - mobile-service
....

== Using the servicename label

Inside of the `apb.yml` file, make sure you use the `serviceName:` label, like:

....
...
metadata:
  displayName: Aerogear Sync Server
  console.openshift.io/iconClass: icon-nodejs
  serviceName: fh-sync-server
...
....

== Testing an APB

Currently, there are not many tools for testing. The APB team has a few open Github issues and proposals:

* link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/131[lint command for APB content]
* link:https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/proposals/testing.md[CI and Image tests]

== Automated Builds

Every `aerogear` APB has a Docker Hub repository set up for hosting images.
When a PR for an APB repository is merged to master, the Docker Hub respository detects this and kicks off an automated build.
If the build is successful, the resulting image is tagged as `latest`, replacing the previous `latest` image for that APB.

=== Setting up an Automated Build for APB Images

IMPORTANT: Docker repositories for APBs need to be created as an 'Automated Build' rather than a 'Repository'. There doesn't seem to be a way to add an automated build to a repository afterwards.

While signed into Docker Hub from a browser:

* Create > Create Automated Build
* Choose Github and allow access to repositories in the aerogearcatalog Github org
* Look for the repo in the list and click it
* Make sure the Repository Namespace & Name are correct e.g. aerogearcatalog/metrics-apb. Visibility public is fine.
* After creating, go to Build Settings
* Configure 'master' branch to build
* Configure tags that match a name of `/^[0-9.]+/` to build
* Save changes and Trigger a build for `master`. If successful, there should be an image with the 'latest' tag.
