[[local-setup]]
= Local Setup

This walkthrough sets up a locally running OpenShift cluster for:

* developing Mobile Services (via APBs)
* developing the Mobile CLI
* developing the Mobile specific UI in the OpenShift Web Console

[[requirements]]
== Requirements

=== Hardware Requirements
* Please make sure that you have at least *64GiB* of free space on your filesystem 
* for smooth run have 16GiB of RAM

[[tooling-requirements]]
=== Tooling Requirements (Required)

* http://docs.ansible.com/ansible/latest/intro_installation.html[Ansible]
>= 2.3.2.0
* https://hub.docker.com/[Docker Hub account]
* https://docs.docker.com/engine/installation/[Docker]
* https://nodejs.org/en/[Node.js] >= 6.10.0
* `libselinux-python` package (Linux only)
* https://brew.sh[Homebrew] >= 1.3.6 (Mac only)

[[firewall-requirements]]
=== Firewall Requirements (Required)

. Configure the Docker registry _and_ ports required as part
of the cluster setup:
+
* Linux: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux[here]
* Mac: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac[here]

. For Linux (Fedora) we also need to add an extra port to the `dockerc`
zone:
+
[source,sh]
----
firewall-cmd --permanent --zone dockerc --add-port 443/tcp
firewall-cmd --reload
----

[[creating-a-local-cluster]]
== Creating a Local Cluster

[[clone-this-repository]]
=== Clone this repository

[source,bash]
----
git clone https://github.com/aerogear/mobile-core
----

[[install-the-required-ansible-dependencies]]
=== Install the required ansible dependencies:

[source,sh]
----
cd mobile-core
ansible-galaxy install -r ./installer/requirements.yml
----
*Note:* If you encounter a permission error for files under `/etc/ansible/roles/` this is because non-root user does not have write access to the default ansible roles folder.
You can either:

* Allow write access to `/etc/ansible/roles/`
* Run the above command with `--roles-path ./installer/roles/`

[[run-the-ansible-installer]]
=== Run the Ansible Installer

The installer sets up your OpenShift environment with the service catalog and the OpenShift Ansible Broker (OAB).
To run the ansible installer directly and specify any property values:

[source,sh]
----
export DOCKERHUB_USERNAME=<my_dockerhub_username>
export DOCKERHUB_PASSWORD=<my_dockerhub_password>
ansible-playbook ./installer/playbook.yml -e "dockerhub_username=$DOCKERHUB_USERNAME" -e "dockerhub_password=$DOCKERHUB_PASSWORD" --ask-become-pass
----

Alternatively, to run a script that prompts for property values:

[source,sh]
----
./installer/install.sh
----

A DockerHub username and password are currently required because the
OpenShift Ansible Broker (OAB) calls Docker APIs to read/load Ansible Playbook
Bundles from a Docker Hub organisation (defaults to `aerogear`).

NOTE: If the installer fails, run
`make clean` in the repo home directory before running the installer again.

NOTE: If the installer hangs for a really long time or crashes on `oc cluster up` step, check free-space on your filesystem.

*Optional*

You can enable Hawkular metrics by passing `-e 'hawkular_metrics=true'`
as part of your `ansible-playbook` command.

[[local-ui-development]]
== Local UI Development

For developing the OpenShift UI locally, see link:https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/developing-ui-locally.adoc[this guide].

[[creating-mobile-apps]]

*Supported platforms/types*

* Android
* iOS
* Cordova
* Xamarin

== Creating Mobile Apps

Once the installer is complete you should be able to access OpenShift at
https://192.168.37.1:8443/console/. You will need to accept the
self-signed certificate.

[[openshift-ui]]
=== Openshift UI

==== Create a new client

Under the `mobile` tab select `apps` then choose a desired platform for your client app:

Fill the client app form with the proper information:

You can check your recently client app status in your project now (provisioning might take a while):

===== Retrieve an existing client

You can check your client app info by going to `Applications > Provisioned Services` and selecting your client app:

===== Delete an existing client

You can delete your client app by clicking on `Actions > Delete` under the client app details:

You will also need to manually delete the client app secret (`Resources > Secrets`):

Then delete it by clicking on `Edit > Delete` in the client app secret detail page:


[[mobile-cli]]
=== Mobile CLI

==== Usage

===== Create a new client

Command:

```
mobile create client $type $unique_id $package_name [flags]
```

Example:

```
mobile create client android helloworld-android org.aerogear.helloworld-android [flags]
```

Output:

* id: unique client id in openshift
* name: user defined client app name
* clienttype: client app type
* appidentifier: user defined client app package name/bundle identifier

===== Retrieve an existing client

Command:

```
mobile get client $client_id [flags]
```

Example:

```
mobile get client helloworld-android [flags]
```

Output:

* id: unique client id in openshift
* name: user defined client app name
* clienttype: client app type
* appidentifier: user defined client app package name/bundle identifier
* apikey: client app api key to be used with other openshift mobile services

===== Delete an existing client

Command:

```
mobile delete client $client_id [flags]
```

Example:

```
mobile delete client helloworld-android [flags]
```

Output:

None - returns 0 exit code if successful.

===== Available flags:

* --namespace: openshift namespace to be used (required if using standalone mobile cli)
* --output: cli output format to be used (json, yml, template or table)
* --quiet: will not print unnecessary output to stdout such as warnings


[[next-steps]]
== Next Steps

* To contribute , check out the link:../../README.adoc#contributing[Contributing] section of the README.
