[[local-setup]]
= Local Setup

This walkthrough sets up a locally running OpenShift cluster for:
* developing Mobile Services (via APBs)
* developing the Mobile CLI against
* developing the Mobile specific UI in the OpenShift Web Console

[[requirements]]
== Requirements

[[tooling-requirements]]
=== Tooling Requirements (Required)

* http://docs.ansible.com/ansible/latest/intro_installation.html[Ansible]
>= 2.3.2.0
* https://hub.docker.com/[Docker Hub account]
* https://docs.docker.com/engine/installation/[Docker]
* https://nodejs.org/en/[Node.js] >= 6.10.0
* `libselinux-python` package (Linux only)
* https://brew.sh[Homebrew] >= 1.3.6 (Mac only)

[[firewall-requirements]]
=== Firewall Requirements (Required)

. Configure the Docker registry _and_ ports required as part
of the cluster setup:
+
* Linux: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux[here]
* Mac: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac[here]

. For Linux (Fedora) we also need to add an extra port to the `dockerc`
zone:
+
[source,sh]
----
firewall-cmd --permanent --zone dockerc --add-port 443/tcp
firewall-cmd --reload
----

[[creating-a-local-cluster]]
== Creating a Local Cluster

[[clone-this-repository]]
=== Clone this repository

[source,bash]
----
git clone https://github.com/aerogear/mobile-core
----

[[install-the-required-ansible-dependencies]]
=== Install the required ansible dependencies:

[source,sh]
----
cd mobile-core
ansible-galaxy install -r ./installer/requirements.yml
----
*Note (macOS):* If you're using `ansible` installed via `pip`, you may need create 
a special folder for ansible-roles and run this command with `--roles-path <ansible-roles-folder-path>`,
or run it with `sudo`. This is because non-root user does not have write access to default ansible roles folder (`/etc/ansible/roles`).


[[run-the-ansible-installer]]
=== Run the Ansible Installer

The installer sets up your OpenShift environment with the service catalog and the OpenShift Ansible Broker (OAB).
To run the ansible installer directly and specify any property values:

[source,sh]
----
export DOCKERHUB_USERNAME=<my_dockerhub_username>
export DOCKERHUB_PASSWORD=<my_dockerhub_password>
ansible-playbook ./installer/playbook.yml -e "dockerhub_username=$DOCKERHUB_USERNAME" -e "dockerhub_password=$DOCKERHUB_PASSWORD" --ask-become-pass
----

Alternatively, to run a script that prompts for property values:

[source,sh]
----
./installer/install.sh
----

A DockerHub username and password are currently currently required because the
OpenShift Ansible Broker (OAB) calls Docker APIs to read/load Ansible Playbook
Bundles from a Docker Hub organisation (defaults to `aerogear`).

NOTE: If the installer fails, run
`make clean` in the repo home directory before running the installer again.

*Optional*

You can enable Hawkular metrics by passing `-e 'hawkular_metrics=true'`
as part of your `ansible-playbook` command.

[[local-ui-development]]
== Local UI Development

....
cd ui
grunt local
....

If you see an `ENOSPC` error, you may need to increase the number of
files your user can watch by running this command:

[source,sh]
----
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
----

[[creating-mobile-apps]]
== Creating Mobile Apps

Once the installer is complete you should be able to access OpenShift at
https://192.168.37.1:8443/console/. You will need to accept the
self-signed certificate.

You can login using `developer` and any password.

Once logged in you should be presented with a `catalog` of services.
To create your first Mobile App:

. Choose the `Mobile` category & `Apps` sub-category.
. Choose `Android App`
. Fill in the required information and continue through the wizard.
. The App should appear in the 'Mobile Applications' section of the Project Overview screen

[[next-steps]]
== Next Steps

* To contribute , check out the link:../../README.adoc#contributing[Contributing] section of the README.