---
# tasks file for setup-openshift-admin-user

- name: Login as system admin
  shell: "oc login -u system:admin"

- name: Get admin user
  shell: "oc get user admin"
  register: admin_user
  failed_when: false
  no_log: True

- name: Create admin user
  shell: "oc create user {{ user_name }}"
  when: admin_user.rc == 1

- name: Give admin user permissions
  shell: | 
    oc adm policy add-cluster-role-to-user edit {{ user_name }}
    oc adm policy add-cluster-role-to-user cluster-admin {{ user_name }}
    oc adm policy add-cluster-role-to-user access-asb-role {{ user_name }}