---
# tasks file for setup-openshift-admin-user

- name: Login as system admin
  shell: "oc login -u system:admin"

- name: Get all users
  shell: "oc get user"
  register: all_users

- name: Create admin user
  shell: "oc create user {{ user_name }}"
  when: "user_name not in all_users.stdout"

- name: Give admin user permissions
  shell: "oc adm policy add-cluster-role-to-user edit {{ user_name }}"
