galaxy_info:
  author: Aerogear
  description: Setup Template Service Broker in OpenShift

  issue_tracker_url: https://github.com/aerogear/mobile-core/issues

  license: license (MIT)

  min_ansible_version: 2.2

  platforms:
  - name: macOS
    versions:
    - all
  - name: OSX
    versions:
    - all
  - name: Fedora
    versions:
    - all

  galaxy_tags:
  - aerogear
  - openshift
  - template
  - service
  - broker

dependencies: []
