---

- name: Setup OpenShift cluster with the Mobile Core and Service Brokers
  hosts: localhost
  roles:
  - role: install-socat
    tags: install-socat
  
  - role: openshift-origin-client-tools
    tags: install-oc

  - role: oc-cluster-up
    tags: [oc-cluster-up, local, local-dev]

  - role: template-service-broker-setup
    tags: [setup-tsb, local, local-dev]

  - role: mcp-ui-extension-setup
    tags: [setup-mcp, local, local-dev]

  - role: setup-openshift-admin-user
    tags: [setup-admin-user, local-dev]

  - role: create-mobile-client-crd
    tags: [local, local-dev]
    
  - role: ansible-service-broker-setup
    tags: [setup-asb, local, local-dev]
  vars_files:
  - "vars/mobile-control-panel.yml"
